name: Build Merge

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Create folder
      run: mkdir -p src/main/resources/static/

    - name: Move dist to resource
      run: mv webui/dist/* src/main/resources/static/
