name: "Feature Request"
description: "Suggest an idea for this project"
title: "[Feature] "
labels: ["Feature"]
type: "Feature"

body:
  - type: textarea
    id: description

    attributes:
      label: "Description"
      description: "Clearly describe the feature you want. How do you envision it working?"

    validations:
      required: true
