package moe.shizuki.korrent.bittorrent.model

import com.fasterxml.jackson.annotation.JsonProperty

data class QBittorrentTorrentProperty(
    @field:JsonProperty("addition_date") val additionDate: Long,
    @field:JsonProperty("comment") val comment: String,
    @field:JsonProperty("completion_date") val completionDate: Long,
    @field:JsonProperty("created_by") val createdBy: String,
    @field:JsonProperty("creation_date") val creationDate: Long,
    @field:JsonProperty("dl_limit") val dlLimit: Long,
    @field:JsonProperty("dl_speed") val dlSpeed: Long,
    @field:JsonProperty("dl_speed_avg") val dlSpeedAvg: Long,
    @field:JsonProperty("download_path") val downloadPath: String,
    @field:JsonProperty("eta") val eta: Int,
    @field:JsonProperty("has_metadata") val hasMetadata: Boolean,
    @field:JsonProperty("hash") val hash: String,
    @field:JsonProperty("infohash_v1") val infohashV1: String,
    @field:JsonProperty("infohash_v2") val infohashV2: String,
    @field:JsonProperty("is_private") val isPrivate: Boolean,
    @field:JsonProperty("last_seen") val lastSeen: Long,
    @field:JsonProperty("name") val name: String,
    @field:JsonProperty("nb_connections") val nbConnections: Int,
    @field:JsonProperty("nb_connections_limit") val nbConnectionsLimit: Int,
    @field:JsonProperty("peers") val peers: Int,
    @field:JsonProperty("peers_total") val peersTotal: Int,
    @field:JsonProperty("piece_size") val pieceSize: Int,
    @field:JsonProperty("pieces_have") val piecesHave: Int,
    @field:JsonProperty("pieces_num") val piecesNum: Int,
    @field:JsonProperty("popularity") val popularity: Double,
    @field:JsonProperty("private") val `private`: Boolean,
    @field:JsonProperty("progress") val progress: Double,
    @field:JsonProperty("reannounce") val reannounce: Long,
    @field:JsonProperty("save_path") val savePath: String,
    @field:JsonProperty("seeding_time") val seedingTime: Long,
    @field:JsonProperty("seeds") val seeds: Int,
    @field:JsonProperty("seeds_total") val seedsTotal: Int,
    @field:JsonProperty("share_ratio") val shareRatio: Double,
    @field:JsonProperty("time_elapsed") val timeElapsed: Long,
    @field:JsonProperty("total_downloaded") val totalDownloaded: Long,
    @field:JsonProperty("total_downloaded_session") val totalDownloadedSession: Long,
    @field:JsonProperty("total_size") val totalSize: Long,
    @field:JsonProperty("total_uploaded") val totalUploaded: Long,
    @field:JsonProperty("total_uploaded_session") val totalUploadedSession: Long,
    @field:JsonProperty("total_wasted") val totalWasted: Long,
    @field:JsonProperty("up_limit") val upLimit: Long,
    @field:JsonProperty("up_speed") val upSpeed: Long,
    @field:JsonProperty("up_speed_avg") val upSpeedAvg: Long
)
