name: Build Frontend

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
        cache-dependency-path: webui/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: webui/

    - name: Type check
      shell: bash
      run: ./node_modules/.bin/vue-tsc --build --force
      working-directory: webui/

    - name: Build
      shell: bash
      run: ./node_modules/.bin/vite build
      working-directory: webui/
